### ISSUE TITLE
Add the option to rebuild by date ascending or descending or by date range.

### ISSUE THREAD

**Issue by ivande** [breiti/ajax-thumbnail-rebuild#10]
Title is self explanatory. I'm rebuilding the thumbnails of a 57000 posts website. Imagine how long is taking and until the process is not finished I will not see any change on my most recent posts.

Please consider it.

**Comment by breiti** [comment]
I'd even go a step further and argue that the user either:
* Has a lot of images and wants new ones to be rebuilt first (like you).
* Doesn't have a lot of images and doesn't care about the execution order.

Thus, I'd rather go with making this the default order...
