### ISSUE TITLE
Image crop parameter

### ISSUE THREAD

**Issue by jnorth** [breiti/ajax-thumbnail-rebuild#14]
Is this the official repo? If so I can try to submit a PR.

The crop parameter isn't being respected when adding an image size: `add_image_size( 'screenshot', 500, 500, array( 'center', 'top' ) );`. The resized image will be cropped to the vertical center of the image instead of the top.

See: https://wordpress.org/support/topic/feature-request-use-new-crop-parameter

**Comment by baden03** [comment]
I also forked the plugin and submitted a Pull Request to deal with this issue.
https://github.com/baden03/ajax-thumbnail-rebuild

**Comment by MarcGuay** [comment]
https://github.com/breiti/ajax-thumbnail-rebuild/pull/18

**Comment by RistoNiinemets** [comment]
fixed in 52c2876
