### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by shankie-san** [breiti/ajax-thumbnail-rebuild#19]
Would you be able to add PHP7 support? I'm getting the following error:

`<b>Deprecated</b>:  Methods with the same name as their class will not be constructors in a future version of PHP; AjaxThumbnailRebuild has a deprecated constructor in <b>/var/www/html/wp-content/plugins/ajax-thumbnail-rebuild/ajax-thumbnail-rebuild.php</b> on line <b>26</b><br />`

Thanks!

**Comment by baden03** [comment]
The issue with PHP7 not being supported by AJAX Thumbnail Rebuild is verified on our end as well.
If the plugin is not going to be updated, please let us know so we can find an alternative.

**Comment by wgroenewold** [comment]
https://wordpress.org/support/topic/not-php-70-compatible-1/
