### ISSUE TITLE
Maintaining this plugin

### ISSUE THREAD

**Issue by RistoNiinemets** [breiti/ajax-thumbnail-rebuild#21]
Hello @breiti,

First of all, I want to thank you for the great plugin.

I tried looking up your contacts to get a hold of you, but did not find any, so I'll write here and hope you will see it.

"Ajax Thumbnail Rebuild" has a lot of installations (over 100 000 based on WordPress.org statistics), so it is quite popular. I like that it is really simple and does the trick. However, the plugin's code is outdated and needs to be updated.

As I use this plugin quite often, I am willing to take over the development and maintaining of the plugin. My promise is, that I will not make it a "premium" plugin, nor will advertise myself or allow any kind of advertisements in the plugin. 

There are people out there also wanting this plugin developed and updated (as seen from the pull requests).

To get the things rolling, I need you to add me to the admin, moderator or what ever role is here on Github for this repostory, so I could make direct commits to it and merge pull requests. Also a contributor status to WordPress.org repository, so I could do the same things there.

Github - Repository - Settings - Collaborators & Teams - Add "RistoNiinemets"
WordPress.org - add "ristoniinemets" to the plugins readme.txt file through SVN

Looking forward to your reply.

Best of wishes,
Risto

**Comment by breiti** [comment]
I'm glad somebody is willing to take over development of this plugin. As life is keeping me busy, I was looking for somebody to do this for some time now. I really appreciate your willingness to maintain this plugin and I've added you as a contributor here on github, as well as on wordpress.org. Hopefully this will bring new life to this plugin ;-)

**Comment by RistoNiinemets** [comment]
Thank you @breiti!
