### ISSUE TITLE
Invalid Crop-Check

### ISSUE THREAD

**Issue by karlkowald** [breiti/ajax-thumbnail-rebuild#30]
Hi, just descripted the problem (and solution) there:
https://wordpress.org/support/topic/bug-found-in-plugincode/

Hi, within your Plugin you made a small bug, which disallows to set the Crop-Parameter as an array.

In Line 337 you check, if your own crop-information which is per default set to false is not an array and after that you return the the array as (intval).

so you have to change the line from:
if( ! is_array( $sizes[$s][‘crop’] ) ) {
to
if( ! is_array( $_wp_additional_image_sizes[$s][‘crop’] ) ) {

After that its correct and working as intended. please update your plugin with this fix. thanks 🙂

Another hint: update the link to github, cause now its referencing back to wordpress plugin directory.

**Comment by RistoNiinemets** [comment]
Fixed with #31 , thanks
